I just build

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,9 +1,9 @@
-name: ci
+name: CI/CD Pipeline
 
 on: 
   push:
     branches: 
-      - origin
+      - master  # Change 'main' to the branch you want to trigger the action
 
 jobs: 
   Build:
@@ -11,55 +11,51 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Repository
-      uses: actions/checkout@v2
-    - name: greeting
-      run: echo "Hello World users"  
+      - name: Checkout Repository
+        uses: actions/checkout@v2
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
-      with:
-        node-version: 20
+      - name: Greeting
+        run: echo "Hello World users"  
 
-    - name: Install Dependencies
-      run: npm Install
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: 20
 
-    - name: Build Docker Image
-      env:
-        image_name: app_test_image
-        version: 1.0.0
-        username: oluwaseun7
-      run: |
-        docker build -t $username/$image_name:$version .
+      - name: Install Dependencies
+        run: npm install
 
-    - name: Login to Docker Hub Account
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_PASSWORD }}
+      - name: Build Docker Image
+        env:
+          image_name: app_test_image
+          version: 1.0.0
+          username: oluwaseun7
+        run: |
+          docker build -t $username/$image_name:$version .
 
-    - name: Push Docker Image to Docker Hub
-      env:
-        image_name: app_test_image
-        version: 1.0.0
-        username: oluwaseun7
-      run: |
-        docker push $username/$image_name:$version
+      - name: Login to Docker Hub Account
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-    - name: install Trivy
-      run: |
-        sudo apt-get install -y wget
-        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.57.0_Linux-64bit.deb
-        sudo dpkg -i trivy_0.57.0_Linux-64bit.deb
+      - name: Push Docker Image to Docker Hub
+        env:
+          image_name: app_test_image
+          version: 1.0.0
+          username: oluwaseun7
+        run: |
+          docker push $username/$image_name:$version
 
-    - name: Scan Docker Image for Vulnerabilities
-      run: |
-        trivy image --exit-code 1 --severity HIGH,CRITICAL ${username}/${image_name}:${version} || true
+      - name: Scan Docker Image for Vulnerabilities
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/app_test_image:1.0.0
 
-    - name: Run Tests
-      run: |
-        echo run test
-        npm test || { echo 'Tests failed'; exit 1; }
+      - name: Run Tests
+        run: |
+          echo "Running tests..."
+          npm test || { echo 'Tests failed'; exit 1; }
 
   Deploy:
     name: Deploy Docker Image
@@ -67,17 +63,20 @@ jobs:
     needs: Build
     steps:
       - name: Checkout Repository
-        uses: actions/checkout@v3
-      - name: "Logs into Docker Hub Account!"
+        uses: actions/checkout@v2
+
+      - name: Login to Docker Hub Account
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
       - name: Pull and Deploy Docker Image
         env:
-          image_name: test-image # Image name variable
-          version: 1.0.0 # Image version variable
+          image_name: app_test_image
+          version: 1.0.0
           username: oluwaseun7
         run: |
           docker pull $username/$image_name:$version
-          docker run -d -p 808:80 $username/$image_name:$version
+          docker run -d -p 8080:80 $username/$image_name:$version
+
